### ISSUE TITLE
Nil point pack when adding an exporter without a stopFunc pointer

### ISSUE THREAD

**Issue by huikang** [open-telemetry/opentelemetry-service#244]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2716629]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-service/service/builder.(*builtExporter).Stop(...)
	/Users/huikang/research/projects/src/github.com/huikang/opentelemetry-service/service/builder/exporters_builder.go:39
github.com/open-telemetry/opentelemetry-service/service/builder.Exporters.StopAll(0xc00065ac00)
	/Users/huikang/research/projects/src/github.com/huikang/opentelemetry-service/service/builder/exporters_builder.go:48 +0x79
github.com/open-telemetry/opentelemetry-service/service.(*Application).shutdownPipelines(0xc00031c000)
	/Users/huikang/research/projects/src/github.com/huikang/opentelemetry-service/service/service.go:242 +0x79
github.com/open-telemetry/opentelemetry-service/service.(*Application).executeUnified(0xc00031c000)
	/Users/huikang/research/projects/src/github.com/huikang/opentelemetry-service/service/service.go:268 +0x2d0
github.com/open-telemetry/opentelemetry-service/service.(*Application).StartUnified.func1(0xc00017cf00, 0xc00009bf20, 0x0, 0x2)
	/Users/huikang/research/projects/src/github.com/huikang/opentelemetry-service/service/service.go:284 +0x3d
github.com/spf13/cobra.(*Command).execute(0xc00017cf00, 0xc0000c6010, 0x2, 0x2, 0xc00017cf00, 0xc0000c6010)
	/Users/huikang/research/projects/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc00017cf00, 0xc00017cf00, 0xc00002fef8, 0x6)
	/Users/huikang/research/projects/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/huikang/research/projects/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/open-telemetry/opentelemetry-service/service.(*Application).StartUnified(0xc00031c000, 0xc000636750, 0xc000636720)
	/Users/huikang/research/projects/src/github.com/huikang/opentelemetry-service/service/service.go:296 +0x154
main.main()
	/Users/huikang/research/projects/src/github.com/huikang/opentelemetry-service/cmd/otelsvc/main.go:37 +0xd0

```

To reproduce, start a otel agent with the following configuration and ctrl-C to quit

```
exporters:
  opencensus:
    endpoint: "otel-collector:55678"
    # disabled: true
  logging:

processors:
  batch:
  queued-retry:

pipelines:
  traces:
    receivers: [jaeger]
    exporters: [logging]
    processors: [batch, queued-retry]
```

This is caused by an exporter without any stopFunc because its exporter.stop is not set [1] in any pipeline.

[1] https://github.com/open-telemetry/opentelemetry-service/blob/f20385bac8e7a3db68a1f8cfeaa3a3edcde9f419/service/builder/exporters_builder.go#L178-L206

**Comment by tigrannajaryan** [comment]
Done.
