### ISSUE TITLE
test: mem ballast test fails on Darwin

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-service#58]
```terminal
--- FAIL: TestApplication_MemBallast (1.01s)
panic: open /proc/11006/stat: no such file or directory [recovered]
        panic: open /proc/11006/stat: no such file or directory

goroutine 220 [running]:
testing.tRunner.func1(0xc0008fa000)
        /usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:830 +0x69d
panic(0x37383c0, 0xc000270840)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/open-telemetry/opentelemetry-service/cmd/occollector/app/collector.testMemBallast(0xc0008fa000, 0xc0008a2100, 0x0)
        /Users/pj/go/src/github.com/open-telemetry/opentelemetry-service/cmd/occollector/app/collector/collector_test.go:145 +0x8eb
github.com/open-telemetry/opentelemetry-service/cmd/occollector/app/collector.TestApplication_MemBallast(0xc0008fa000)
        /Users/pj/go/src/github.com/open-telemetry/opentelemetry-service/cmd/occollector/app/collector/collector_test.go:168 +0x97
testing.tRunner(0xc0008fa000, 0x3b31930)
        /usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
        /usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:916 +0x65b
FAIL    github.com/open-telemetry/opentelemetry-service/cmd/occollector/app/collector   2.174s
```

**Comment by tigrannajaryan** [comment]
@owais looks like non-portable code.

**Comment by owais** [comment]
I'll try to fix it tomorrow. Please assign to me (I can't find a way to assign myself).

**Comment by owais** [comment]
This was fixed in https://github.com/open-telemetry/opentelemetry-service/pull/85 and can be closed
